import { User, Post, Message, Conversation, Notification } from '@/types';

export const MOCK_USERS: User[] = [
    // --- CREATORS ---
    {
        id: 'creator_1',
        email: 'amara@moyo.com',
        username: 'Amara_Lagos',
        displayName: 'Amara Lagos',
        role: 'creator',
        accountType: 'creator',
        age: 21,
        dateOfBirth: { day: 15, month: 6, year: 2003 },
        ageVerified: true,
        country: 'Nigeria',
        countryCode: 'NG',
        countryFlag: '🇳🇬',
        city: 'Lagos',
        bio: 'Fashion designer & model bringing African luxury to the world. 🧵✨',
        avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
        coverImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=1200&h=400&fit=crop',
        category: 'Fashion',
        followers: ['fan_1', 'fan_2'],
        following: ['creator_2', 'creator_3'],
        followersCount: 2340,
        followingCount: 45,
        subscribedTo: [],
        isVerified: true,
        verificationStatus: 'verified',
        subscribers: ['fan_1'],
        subscribersCount: 890,
        subscriptionPrice: 5000,
        subscriptionTiers: [
            { name: 'Basic', price: 2500 },
            { name: 'VIP', price: 5000 },
        ],
        totalPosts: 124,
        totalLikes: 15400,
        totalViews: 45000,
        totalEarnings: 890000,
        engagementRate: 5.4,
        canPost: true,
        contentRating: 'sfw',
        allowExplicitContent: false,
        messagingEnabled: true,
        messagingPrice: 500,
        autoAcceptMessages: false,
        isOnline: true,
        lastSeen: Date.now(),
        createdAt: Date.now() - 10000000,
        lastPostAt: Date.now() - 3600000, // 1 hour ago
        isLoggedIn: false,
        notInterested: []
    },
    {
        id: 'creator_2',
        email: 'kwame@moyo.com',
        username: 'Kwame_Accra',
        displayName: 'Kwame Accra',
        role: 'creator',
        accountType: 'creator',
        age: 25,
        dateOfBirth: { day: 22, month: 3, year: 1999 },
        ageVerified: true,
        country: 'Ghana',
        countryCode: 'GH',
        countryFlag: '🇬🇭',
        city: 'Accra',
        bio: 'Fitness and Wellness coach. 💪🏾 Transform your body with me.',
        avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
        coverImage: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1200&h=400&fit=crop',
        category: 'Fitness',
        followers: ['fan_1'],
        following: ['creator_1'],
        followersCount: 1890,
        followingCount: 30,
        subscribedTo: [],
        isVerified: true,
        verificationStatus: 'verified',
        subscribers: [],
        subscribersCount: 650,
        subscriptionPrice: 4000,
        subscriptionTiers: [{ name: 'Training', price: 4000 }],
        totalPosts: 89,
        totalLikes: 12000,
        totalViews: 30000,
        totalEarnings: 450000,
        engagementRate: 6.2,
        canPost: true,
        contentRating: 'sfw',
        allowExplicitContent: false,
        messagingEnabled: true,
        messagingPrice: 200,
        autoAcceptMessages: true,
        isOnline: false,
        lastSeen: Date.now() - 3600000,
        createdAt: Date.now() - 9000000,
        lastPostAt: Date.now() - 86400000,
        isLoggedIn: false,
        notInterested: []
    },
    {
        id: 'creator_3',
        email: 'zara@moyo.com',
        username: 'Zara_Nairobi',
        displayName: 'Zara Nairobi',
        role: 'creator',
        accountType: 'creator',
        age: 28,
        dateOfBirth: { day: 10, month: 11, year: 1996 },
        ageVerified: true,
        country: 'Kenya',
        countryCode: 'KE',
        countryFlag: '🇰🇪',
        city: 'Nairobi',
        bio: 'Lifestyle & Travel. exploring the beauty of East Africa. 🌍✈️',
        avatar: 'https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=400&h=400&fit=crop',
        coverImage: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=1200&h=400&fit=crop',
        category: 'Lifestyle',
        followers: ['fan_1', 'fan_3'],
        following: [],
        followersCount: 3120,
        followingCount: 120,
        subscribedTo: [],
        isVerified: true,
        verificationStatus: 'verified',
        subscribers: ['fan_1', 'fan_3'],
        subscribersCount: 1200,
        subscriptionPrice: 6000,
        subscriptionTiers: [{ name: 'Premium', price: 6000 }],
        totalPosts: 210,
        totalLikes: 25000,
        totalViews: 80000,
        totalEarnings: 1200000,
        engagementRate: 4.8,
        canPost: true,
        contentRating: 'sfw',
        allowExplicitContent: false,
        messagingEnabled: true,
        messagingPrice: 1000,
        autoAcceptMessages: false,
        isOnline: true,
        lastSeen: Date.now(),
        createdAt: Date.now() - 15000000,
        isLoggedIn: false
    },
    {
        id: 'creator_4',
        email: 'jabari@moyo.com',
        username: 'Jabari_Joburg',
        displayName: 'Jabari Joburg',
        role: 'creator',
        accountType: 'creator',
        age: 24,
        dateOfBirth: { day: 5, month: 2, year: 2000 },
        ageVerified: true,
        country: 'South Africa',
        countryCode: 'ZA',
        countryFlag: '🇿🇦',
        city: 'Johannesburg',
        bio: 'Music Producer & DJ. 🎵🎧 Amapiano to the world.',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
        coverImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&h=400&fit=crop',
        category: 'Music',
        followers: ['fan_2'],
        following: [],
        followersCount: 2560,
        followingCount: 85,
        subscribedTo: [],
        isVerified: true,
        verificationStatus: 'verified',
        subscribers: ['fan_2'],
        subscribersCount: 980,
        subscriptionPrice: 3500,
        subscriptionTiers: [{ name: 'Backstage', price: 3500 }],
        totalPosts: 65,
        totalLikes: 9800,
        totalViews: 22000,
        totalEarnings: 300000,
        engagementRate: 7.1,
        canPost: true,
        contentRating: 'sfw',
        allowExplicitContent: false,
        messagingEnabled: true,
        messagingPrice: 300,
        autoAcceptMessages: true,
        isOnline: false,
        lastSeen: Date.now() - 7200000,
        createdAt: Date.now() - 5000000,
        isLoggedIn: false
    },
    {
        id: 'creator_5',
        email: 'imani@moyo.com',
        username: 'Imani_Cairo',
        displayName: 'Imani Cairo',
        role: 'creator',
        accountType: 'creator',
        age: 26,
        dateOfBirth: { day: 18, month: 8, year: 1998 },
        ageVerified: true,
        country: 'Egypt',
        countryCode: 'EG',
        countryFlag: '🇪🇬',
        city: 'Cairo',
        bio: 'Digital Artist & Illustrator. 🎨 Creating dreams.',
        avatar: 'https://images.unsplash.com/photo-1531123414780-f742464d8ce8?w=400&h=400&fit=crop',
        coverImage: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&h=400&fit=crop',
        category: 'Art',
        followers: ['fan_2'],
        following: [],
        followersCount: 1750,
        followingCount: 150,
        subscribedTo: [],
        isVerified: true,
        verificationStatus: 'verified',
        subscribers: ['fan_2'],
        subscribersCount: 580,
        subscriptionPrice: 3000,
        subscriptionTiers: [{ name: 'Gallery', price: 3000 }],
        totalPosts: 95,
        totalLikes: 14500,
        totalViews: 35000,
        totalEarnings: 250000,
        engagementRate: 6.5,
        canPost: true,
        contentRating: 'sfw',
        allowExplicitContent: false,
        messagingEnabled: true,
        messagingPrice: 0, // Free messaging
        autoAcceptMessages: true,
        isOnline: true,
        lastSeen: Date.now(),
        createdAt: Date.now() - 12000000,
        isLoggedIn: false
    },
    {
        id: 'creator_pending',
        email: 'pending@moyo.com',
        username: 'Pending_Creator',
        displayName: 'Pending Creator',
        role: 'creator',
        accountType: 'creator',
        age: 22,
        dateOfBirth: { day: 1, month: 1, year: 2002 },
        ageVerified: true,
        country: 'Ghana',
        countryCode: 'GH',
        countryFlag: '🇬🇭',
        city: 'Kumasi',
        bio: 'New here! waiting for verification.',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Pending',
        coverImage: '',
        category: 'Lifestyle',
        followers: [],
        following: [],
        followersCount: 0,
        followingCount: 0,
        subscribedTo: [],
        isVerified: false,
        verificationStatus: 'pending',
        subscribers: [],
        subscribersCount: 0,
        subscriptionPrice: 0,
        subscriptionTiers: [],
        totalPosts: 0,
        totalLikes: 0,
        totalViews: 0,
        totalEarnings: 0,
        engagementRate: 0,
        canPost: false, // CANNOT POST YET
        contentRating: 'sfw',
        allowExplicitContent: false,
        messagingEnabled: false,
        messagingPrice: 0,
        autoAcceptMessages: false,
        isOnline: false,
        lastSeen: Date.now(),
        createdAt: Date.now(),
        isLoggedIn: false
    },

    // --- FANS ---
    {
        id: 'fan_1',
        email: 'fan1@test.com',
        username: 'Fan_User1',
        displayName: 'Fan User 1',
        role: 'fan',
        accountType: 'fan',
        age: 19,
        dateOfBirth: { day: 12, month: 5, year: 2005 },
        ageVerified: true,
        country: 'Nigeria',
        countryCode: 'NG',
        countryFlag: '🇳🇬',
        bio: 'Just here for the content.',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fan1',
        coverImage: '',
        category: '',
        followers: [],
        following: ['creator_1', 'creator_2', 'creator_3'],
        followersCount: 0,
        followingCount: 15,
        subscribedTo: ['creator_1', 'creator_3'],
        isVerified: false,
        verificationStatus: 'pending',
        subscribers: [],
        subscribersCount: 0,
        subscriptionPrice: 0,
        subscriptionTiers: [],
        totalPosts: 0,
        totalLikes: 0,
        totalViews: 0,
        totalEarnings: 0,
        engagementRate: 0,
        canPost: false,
        contentRating: 'sfw',
        allowExplicitContent: false,
        messagingEnabled: false,
        messagingPrice: 0,
        autoAcceptMessages: false,
        isOnline: true,
        lastSeen: Date.now(),
        createdAt: Date.now(),
        isLoggedIn: false
    },
    {
        id: 'fan_2',
        email: 'fan2@test.com',
        username: 'Fan_User2',
        displayName: 'Fan User 2',
        role: 'fan',
        accountType: 'fan',
        age: 23,
        dateOfBirth: { day: 20, month: 9, year: 2001 },
        ageVerified: true,
        country: 'South Africa',
        countryCode: 'ZA',
        countryFlag: '🇿🇦',
        bio: 'Music and Art lover.',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fan2',
        coverImage: '',
        category: '',
        followers: [],
        following: ['creator_4', 'creator_5'],
        followersCount: 0,
        followingCount: 8,
        subscribedTo: ['creator_4', 'creator_5'],
        isVerified: false,
        verificationStatus: 'pending',
        subscribers: [],
        subscribersCount: 0,
        subscriptionPrice: 0,
        subscriptionTiers: [],
        totalPosts: 0,
        totalLikes: 0,
        totalViews: 0,
        totalEarnings: 0,
        engagementRate: 0,
        canPost: false,
        contentRating: 'sfw',
        allowExplicitContent: false,
        messagingEnabled: false,
        messagingPrice: 0,
        autoAcceptMessages: false,
        isOnline: false,
        lastSeen: Date.now() - 8000000,
        createdAt: Date.now(),
        isLoggedIn: false
    },
    {
        id: 'fan_3',
        email: 'fan3@test.com',
        username: 'Fan_User3',
        displayName: 'Fan User 3',
        role: 'fan',
        accountType: 'fan',
        age: 26,
        dateOfBirth: { day: 3, month: 12, year: 1998 },
        ageVerified: true,
        country: 'Kenya',
        countryCode: 'KE',
        countryFlag: '🇰🇪',
        bio: '',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fan3',
        coverImage: '',
        category: '',
        followers: [],
        following: ['creator_3'],
        followersCount: 0,
        followingCount: 20,
        subscribedTo: ['creator_3'],
        isVerified: false,
        verificationStatus: 'pending',
        subscribers: [],
        subscribersCount: 0,
        subscriptionPrice: 0,
        subscriptionTiers: [],
        totalPosts: 0,
        totalLikes: 0,
        totalViews: 0,
        totalEarnings: 0,
        engagementRate: 0,
        canPost: false,
        contentRating: 'sfw',
        allowExplicitContent: false,
        messagingEnabled: false,
        messagingPrice: 0,
        autoAcceptMessages: false,
        isOnline: true,
        lastSeen: Date.now(),
        createdAt: Date.now(),
        isLoggedIn: false
    }
];

export const MOCK_POSTS: Post[] = [
    {
        id: 'post_1',
        creatorId: 'creator_1',
        creatorUsername: 'Amara_Lagos',
        creatorAvatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
        creatorCountry: 'Nigeria',
        type: 'photo',
        mediaUrls: ['https://images.unsplash.com/photo-1529139574466-a302d2d3f52c?w=1200&fit=crop'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1529139574466-a302d2d3f52c?w=400&fit=crop',
        caption: 'New collection drop! 🌿 Keeping it natural and elegant. Use code AMARA20 for discount.',
        isNSFW: false,
        tags: ['fashion', 'style', 'nigeria'],
        category: 'Fashion',
        visibility: 'free',
        price: 0,
        likes: 1240,
        likedBy: ['fan_1'],
        comments: 45,
        shares: 12,
        views: 3400,
        saves: 89,
        status: 'published',
        publishedAt: Date.now() - 3600000,
        createdAt: Date.now() - 3600000,
        updatedAt: Date.now() - 3600000,
        revenue: 0,
        views_from_subscribers: 0,
        conversion_rate: 0
    },
    {
        id: 'post_2',
        creatorId: 'creator_1',
        creatorUsername: 'Amara_Lagos',
        creatorAvatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
        creatorCountry: 'Nigeria',
        type: 'photo',
        mediaUrls: ['https://images.unsplash.com/photo-1550614000-4b9519e02a15?w=1200&fit=crop'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1550614000-4b9519e02a15?w=400&fit=crop',
        caption: 'Exclusive backstage look at my runway show. This is what chaos looks like! 😂',
        isNSFW: false,
        tags: ['backstage', 'runway', 'exclusive'],
        category: 'Fashion',
        visibility: 'subscribers',
        price: 0,
        likes: 850,
        likedBy: ['fan_1', 'fan_2'],
        comments: 67,
        shares: 5,
        views: 1200,
        saves: 45,
        status: 'published',
        publishedAt: Date.now() - 86400000,
        createdAt: Date.now() - 86400000,
        updatedAt: Date.now() - 86400000,
        revenue: 0,
        views_from_subscribers: 0,
        conversion_rate: 0
    },
    {
        id: 'post_3',
        creatorId: 'creator_3',
        creatorUsername: 'Zara_Nairobi',
        creatorAvatar: 'https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=400&h=400&fit=crop',
        creatorCountry: 'Kenya',
        type: 'video',
        mediaUrls: ['https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=1200&fit=crop'], // Placeholder image for video
        thumbnailUrl: 'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=400&fit=crop',
        caption: 'Safari sunset vlog 🌅. The lions were so close today!',
        isNSFW: false,
        tags: ['safari', 'kenya', 'travel'],
        category: 'Lifestyle',
        visibility: 'free',
        price: 0,
        likes: 2100,
        likedBy: ['fan_1', 'fan_3'],
        comments: 120,
        shares: 450,
        views: 5600,
        saves: 210,
        status: 'published',
        publishedAt: Date.now() - 172800000,
        createdAt: Date.now() - 172800000,
        updatedAt: Date.now() - 172800000,
        revenue: 0,
        views_from_subscribers: 0,
        conversion_rate: 0
    },
    {
        id: 'post_4',
        creatorId: 'creator_4',
        creatorUsername: 'Jabari_Joburg',
        creatorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
        creatorCountry: 'South Africa',
        type: 'photo',
        mediaUrls: ['https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&fit=crop'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&fit=crop',
        caption: 'Studio session. New beat cooking. 🔥🎹 Lock in with me.',
        isNSFW: false,
        tags: ['music', 'amapiano', 'studio'],
        category: 'Music',
        visibility: 'free',
        price: 0,
        likes: 1540,
        likedBy: ['fan_2'],
        comments: 89,
        shares: 230,
        views: 4100,
        saves: 120,
        status: 'published',
        publishedAt: Date.now() - 259200000,
        createdAt: Date.now() - 259200000,
        updatedAt: Date.now() - 259200000,
        revenue: 0,
        views_from_subscribers: 0,
        conversion_rate: 0
    },
    {
        id: 'post_5',
        creatorId: 'creator_5',
        creatorUsername: 'Imani_Cairo',
        creatorAvatar: 'https://images.unsplash.com/photo-1531123414780-f742464d8ce8?w=400&h=400&fit=crop',
        creatorCountry: 'Egypt',
        type: 'photo',
        mediaUrls: ['https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&fit=crop'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&fit=crop',
        caption: 'Finished this piece today. "Desert Rose". Digital oil on canvas. 🌹',
        isNSFW: false,
        tags: ['art', 'digitalart', 'egypt'],
        category: 'Art',
        visibility: 'free',
        price: 0,
        likes: 3200,
        likedBy: ['fan_2'],
        comments: 156,
        shares: 67,
        views: 8900,
        saves: 560,
        status: 'published',
        publishedAt: Date.now() - 10000000,
        createdAt: Date.now() - 10000000,
        updatedAt: Date.now() - 10000000,
        revenue: 0,
        views_from_subscribers: 0,
        conversion_rate: 0
    }
];

export const MOCK_MESSAGES: Message[] = [
    {
        id: 'msg_1',
        conversationId: 'conv_1',
        senderId: 'fan_1',
        senderUsername: 'Fan_User1',
        senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fan1',
        recipientId: 'creator_1',
        recipientUsername: 'Amara_Lagos',
        type: 'text',
        content: 'Hi Amara! Absolutely love your new collection. Do you ship to Abuja?',
        isRead: true,
        readAt: Date.now() - 85000000,
        createdAt: Date.now() - 86400000
    },
    {
        id: 'msg_2',
        conversationId: 'conv_1',
        senderId: 'creator_1',
        senderUsername: 'Amara_Lagos',
        senderAvatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
        recipientId: 'fan_1',
        recipientUsername: 'Fan_User1',
        type: 'text',
        content: 'Hey! Yes we do. Express shipping is available properly. Thank you for the love! ❤️',
        isRead: true,
        readAt: Date.now() - 84000000,
        createdAt: Date.now() - 85000000
    },
    {
        id: 'msg_3',
        conversationId: 'conv_1',
        senderId: 'fan_1',
        senderUsername: 'Fan_User1',
        senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fan1',
        recipientId: 'creator_1',
        recipientUsername: 'Amara_Lagos',
        type: 'text',
        content: 'Perfect, ordering now!',
        isRead: false,
        createdAt: Date.now() - 3600000
    }
];

export const MOCK_CONVERSATIONS: Conversation[] = [
    {
        id: 'conv_1',
        participants: ['fan_1', 'creator_1'],
        participantDetails: [
            {
                userId: 'fan_1',
                username: 'Fan_User1',
                avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fan1',
                role: 'fan',
                isOnline: true,
                lastSeen: Date.now()
            },
            {
                userId: 'creator_1',
                username: 'Amara_Lagos',
                avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
                role: 'creator',
                isOnline: true,
                lastSeen: Date.now()
            }
        ],
        lastMessage: 'Perfect, ordering now!',
        lastMessageAt: Date.now() - 3600000,
        lastMessageSenderId: 'fan_1',
        unreadCount: { 'creator_1': 1, 'fan_1': 0 },
        isPaid: false,
        createdAt: Date.now() - 86400000,
        updatedAt: Date.now() - 3600000
    }
];
